import type { SpirVModule } from "./module.js";
import type { SpirVOp, SpirVType } from "./types.js";

/**
 * Generates C code from a SPIR-V IR module.
 * The C code can then be compiled to SPIR-V using glslangValidator or similar.
 */
export class CCodegen {
  /** Generate C source code from a SPIR-V module */
  generate(module: SpirVModule): string {
    const lines: string[] = [];
    lines.push("// Generated by @yalumba/spirv codegen");
    lines.push("#include <stdint.h>");
    lines.push("");

    for (const fn of module.functions) {
      const returnTypeStr = this.typeToC(fn.returnType);
      const params = fn.params.map((p, i) => `${this.typeToC(p)} param_${i}`).join(", ");
      lines.push(`${returnTypeStr} ${fn.name}(${params || "void"}) {`);

      for (const op of fn.body) {
        lines.push(`  ${this.opToC(op)}`);
      }

      lines.push("}");
      lines.push("");
    }

    return lines.join("\n");
  }

  private typeToC(type: SpirVType): string {
    switch (type.kind) {
      case "scalar":
        return this.scalarToC(type.scalar);
      case "vector":
        return `${this.scalarToC(type.element)}[${type.width}]`;
      case "pointer":
        return `${this.typeToC(type.pointee)}*`;
      case "array":
        return `${this.typeToC(type.element)}[${type.length}]`;
    }
  }

  private scalarToC(scalar: string): string {
    switch (scalar) {
      case "void": return "void";
      case "bool": return "int";
      case "u32": return "uint32_t";
      case "i32": return "int32_t";
      case "f32": return "float";
      case "f64": return "double";
      default: return "uint32_t";
    }
  }

  private opToC(op: SpirVOp): string {
    const resultDecl = op.resultType
      ? `${this.typeToC(op.resultType)} r${op.id} = `
      : "";

    switch (op.op) {
      case "OpConstant":
        return `${resultDecl}${op.operands[0]};`;
      case "OpLoad":
        return `${resultDecl}*r${op.operands[0]};`;
      case "OpStore":
        return `*r${op.operands[0]} = r${op.operands[1]};`;
      case "OpIAdd":
        return `${resultDecl}r${op.operands[0]} + r${op.operands[1]};`;
      case "OpIMul":
        return `${resultDecl}r${op.operands[0]} * r${op.operands[1]};`;
      case "OpBitwiseAnd":
        return `${resultDecl}r${op.operands[0]} & r${op.operands[1]};`;
      case "OpShiftRightLogical":
        return `${resultDecl}r${op.operands[0]} >> r${op.operands[1]};`;
      default:
        return `// Unknown op: ${op.op}`;
    }
  }
}
